# -*- encoding: utf-8 -*-
##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see http://www.gnu.org/licenses/.
#
##############################################################################
{
    "name": "Procurements Plan",
    "version": "1.0",
    "author": "OdooMRP team",
    "category": "Procurements",
    "website": "http://www.odoomrp.com",
    "description": """
    This module performs the following:

    1.- This module creates the new object Procurement Plan, with these fields:

        1.1.- Description, type char.
        1.2.- Sequence, type char. It has created a new sequence to this new
              object, this field will be calculated automatically.
        1.3.- From date, type date. Condition for select procurements.
        1.4.- To date, type date. Condition for select procurements.
        1.5.- Project, type many2one to project object, is required.
        1.6.- Procurements, type one2many. Procurements to treat. May be
              imported procurements that are between the dates of points 1.3,
              and 1.4, with state 'running', or 'confirmed'.
        1.7.- Purchases, type one2many. Purchases generated by executing the
              Plan Procurements.

        When procurements run from the plan, all Procurements and generated
        purchases, be associated with the plan.

    2.- In procurement.order object, has added a new field: Plan.
    3.- In purchase.order object, has added a nes field: Plan.
    """,
    "depends": ['procurement',
                'project',
                'stock',
                'purchase',
                'sale',
                'sale_stock'
                ],
    "data": ['data/workflow.xml',
             'data/sequence.xml',
             'security/procurements_with_plan.xml',
             'security/ir.model.access.csv',
             'wizard/run_scheduler_with_plan_view.xml',
             'views/procurement_view.xml',
             'views/purchase_order_view.xml',
             'views/procurement_plan_view.xml',
             ],
    "installable": True
}
